"""
report_generator.py
--------------------
Generates a human-readable Markdown incident report for each processed
alert, and a summary CSV across all incidents in a run. These are the
artifacts a SOC analyst would attach to a ticket or send to a manager.
"""

import csv
from pathlib import Path
from datetime import datetime, timezone


def _timestamp_str() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")


def generate_markdown_report(incident: dict, output_dir: str = "reports") -> str:
    Path(output_dir).mkdir(parents=True, exist_ok=True)

    filename = f"{output_dir}/incident_{incident['alert_id']}.md"

    actions_section = "\n".join(
        f"- **{a['action']}** on `{a['target']}` — {a['detail']} _(at {a['timestamp']})_"
        for a in incident["actions_taken"]
    )

    content = f"""# Incident Report: {incident['alert_id']}

| Field | Value |
|---|---|
| **Timestamp** | {incident.get('timestamp', 'N/A')} |
| **Severity** | {incident['severity']}/10 ({incident['severity_label']}) |
| **Classification** | {incident['classification']} |
| **Matched Rule** | {incident['rule_id']} - {incident['rule_name']} |
| **Host** | {incident.get('host', 'N/A')} |
| **Source IP** | {incident.get('source_ip', 'N/A')} |
| **Destination IP** | {incident.get('destination_ip') or 'N/A'} |
| **Username** | {incident.get('username', 'N/A')} |
| **Playbook Executed** | {incident['playbook']} |

## Original Alert

```
{incident.get('raw_message', 'N/A')}
```

## Automated Actions Taken

{actions_section if actions_section else "No actions were necessary."}

## Analyst Notes

_(Add manual investigation notes here if escalated for human review.)_

---
*This report was auto-generated by the SIEM Incident Response Automation pipeline.*
"""

    with open(filename, "w") as f:
        f.write(content)

    return filename


def generate_summary_csv(incidents: list, output_dir: str = "reports") -> str:
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    filename = f"{output_dir}/incident_summary_{_timestamp_str()}.csv"

    fieldnames = [
        "alert_id", "timestamp", "severity", "severity_label",
        "classification", "rule_id", "host", "source_ip",
        "username", "playbook", "num_actions_taken",
    ]

    with open(filename, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for incident in incidents:
            writer.writerow({
                "alert_id": incident["alert_id"],
                "timestamp": incident.get("timestamp", "N/A"),
                "severity": incident["severity"],
                "severity_label": incident["severity_label"],
                "classification": incident["classification"],
                "rule_id": incident["rule_id"],
                "host": incident.get("host", "N/A"),
                "source_ip": incident.get("source_ip", "N/A"),
                "username": incident.get("username", "N/A"),
                "playbook": incident["playbook"],
                "num_actions_taken": len(incident["actions_taken"]),
            })

    return filename
